### ISSUE TITLE
Working with nested frameworks

### ISSUE THREAD

**Issue by ton252** [blender/Rome#188]
I'm trying to use Rome with project that is depended from another with some Carthage dependencies.

The graph will look like this:
```
MainProject(A)
  - Moya
  - ..
  - Framework(libu)
     - PhoneNumberKit
     - ..
```

My Cartfile MainProject(A):

```
git "localpath/ios/frameworks/libui.git" == 0.1.0
github "Moya/Moya" == 12.0
```

My Cartfile Framework(libui):

```
git "localpath/github/input-mask-ios.git" ~> 4.0
github "marmelroy/PhoneNumberKit" ~> 2.5
```

My Rome file:

```
cache:
  local: ~/Library/Caches/Rome
  
repositoryMap:
- libui:
  - name: libui
    type: dynamic
    platforms: [iOS]
- input-mask-ios:
  - name: input-mask
    type: dynamic
    platforms: [iOS]
```

And when I'm trying to download missing frameworks like this:
```
rome download --platform iOS # download missing frameworks (or copy from local cache)
rome list --missing --platform iOS | awk '{print $1}' | xargs carthage bootstrap --platform iOS --cache-builds # list what is missing and update/build if needed
rome list --missing --platform iOS | awk '{print $1}' | xargs rome upload --platform iOS # upload what is missing
```

I'm receiving this error:
No entry found for dependencies input-mask-ios, phonenumberkit in Cartfile.

What I'm doing wrong?
